app:
  address: '127.0.0.1'
  port: 8080
  units: "imperial"
  time_format: 12
  debug: false
  modules:
    weather:
      position: "top_right"
      config:
        api_key: "YOUR_OPENWEATHER_API_KEY"
        type: "current"
        provider: "openweathermap"
        location: ""
        location_id: ""
    clock:
      position: "top_left"
      config:
        type: "digital"
        id: "clock-widget-central"
        timezone: "America/Chicago"
        color: "#999"
        background: "transparent"
        time_format: "%I:%M:%S %p"
        date_format: "%a, %b %d, %Y"
        size: 32
        show_border: false