app:
  address: '127.0.0.1'
  port: 8080
  units: "imperial"
  time_format: 12
  debug: false
  modules:
    weather:
      position: "top_right"
      config:
        api_key: ""
        type: "current"
        provider: "openweathermap"
        location: ""
        location_id: ""